"""
This script set up Anaconda and virtual environment for all nodes incluster.

The cluster is specified in the file `./cluster_manifest.xml`
"""
import xml.etree.ElementTree as ET
import subprocess

class Node:
	def __init__(self, name, hostname, port):
		self.name = name
		self.hostname = hostname
		self.port = port

manifest_path = "cluster_manifest.xml"		# cluster_manifest.xml is the manifest file generated by cloudlab
username = "xinyu"
ns_str = "http://www.geni.net/resources/rspec/3"
ns_dict = {"ns": ns_str}
tree = ET.parse(manifest_path)
cluster_nodes = []

for node in tree.findall('ns:node', ns_dict):
	if node.get('client_id') == "dsnode":	# skip dataset node
		continue
	services = node.find("ns:services", ns_dict)
	login = services.find("ns:login[@username='xinyu']", ns_dict)
	cluster_nodes.append(Node(
		name = node.get('client_id'),
		hostname = login.get('hostname'),
		port = login.get('port')
	))

for cnode in cluster_nodes:
	print("Find node {}: host={}, port={}".format(cnode.name, cnode.hostname, cnode.port))

"""
env_command = "'bash -s' < setup-env-script.sh"
handles = []
for cnode in cluster_nodes:
    handle = subprocess.Popen(
		"ssh -oStrictHostKeyChecking=no -tt -p {port} {username}@{hostname} {command}".format(
			port=cnode.port,
			username=username,
			hostname=cnode.hostname,
			command=env_command,
		),
		shell=True)	# wait one after another, just in case
    handles.append(handle)

for handle in handles:
    handle.wait()
"""

# allocate mroe space to  rootfs for each node
gfs_command = """'sudo -n env RESIZEROOT={} bash -s' < setup-rootfs-script.sh"""
RESIZEROOT=64
handles = []
for cnode in cluster_nodes:
    handle = subprocess.Popen(
		"ssh -oStrictHostKeyChecking=no -p {port} {username}@{hostname} {command}".format(
			port=cnode.port,
			username=username,
			hostname=cnode.hostname,
			command=gfs_command.format(RESIZEROOT),
		),
		shell=True)	# wait one after another, just in case
    handles.append(handle)

for handle in handles:
    handle.wait()
